# Generated by Django 3.2 on 2022-05-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
