# Generated by Django 3.2 on 2022-05-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_bookmodel_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='redate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
