# Generated by Django 3.2 on 2022-05-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_bookmodel_redate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='connection',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='readurl',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='theme',
            field=models.CharField(max_length=200),
        ),
    ]
